### ISSUE TITLE
Strange behavior of the dashboard. 

### ISSUE THREAD

**Issue by zzhao2010** [grafana/xk6-output-prometheus-remote#103]
Firstly thanks for sharing these great dashboards for visualization. They look awesome. 
On the other hand, I saw strange behavior while I was testing the dashboards with my test cases, and I do have question about the data accuracy as the data reporting on the dashboards doesn't look to align with the test result on the command line.

   Let's have the 1st metric "Request Made" on the "Test Result" dashboard as an example. There were 2 values reporting, which is quite confusing. And neither of these values reflected the accurate number of requests being generated over the test case.
    ![image](https://user-images.githubusercontent.com/63174713/218598480-2e9b9361-ecbe-4f1e-bcd4-4811eee66a26.png)
    And if you take a look at the P95 Response Time metric on the dashboard, it was 3x faster than the p95 response time reported in the test summary on command line side.
    ![image](https://user-images.githubusercontent.com/63174713/218598662-790ad955-16c9-428c-9832-5ee9223ee7b7.png)

**Comment by jwcastillo** [comment]
Have you tried the latest version of the dashboard?

**Comment by lagunkov** [comment]
It is better with update, but there is still issue:

With new dashboard:

<img width="1638" alt="image" src="https://user-images.githubusercontent.com/47297651/221608613-c19df5c4-5832-43e7-a88d-ca977fd037b4.png">

but when I decrease time range, I've got other total reqs count
<img width="1624" alt="image" src="https://user-images.githubusercontent.com/47297651/221609136-6ce49e60-df8e-47dd-8775-c1394db0c4d9.png">

Total requests count changes depends on range, but never equals the actual http requests count:
<img width="820" alt="image" src="https://user-images.githubusercontent.com/47297651/221609686-83ae428f-8211-42e0-918e-c8aa15810184.png">

**Comment by jwcastillo** [comment]
@zzhao2010 Do you still have the same problem?

**Comment by jwcastillo** [comment]
🆗 , I  let me check

**Comment by zzhao2010** [comment]
@jwcastillo I ran into other issues with the dashboard. The docker demo package uses v2.40.7 version of Prometheus in the docker-compose file, on the other hand, I had v2.42 (the latest version) on my real env. I saw metrics were missing due to the naming changes of k6 metrics, which breaks this dashboard. However I changed the version of Prometheus to v2.42 in the docker-compose file, I was not able to re-produce the issue on docker. But I do see there was a [ticket](https://community.k6.io/t/v0-42-prometheus-metrics-missing/5682/15) open already in the community with the issue.

**Comment by zzhao2010** [comment]
@jwcastillo Looks like the issue was fixed with the latest version.
@lagunkov btw, the issue you described above happens on my end as well.. Looks like the values would be messed up if we changed the timeframe. I always use the link in the test list dashboard to the test result dashboard. That way the data reporting would be accurate.

**Comment by soolch** [comment]
Hi, I have this issue also. I found that if the test duration is short, the Request Made metrics is correct, but when test duration go longer, the Request Made metrics will be less than the exact request made count. I did a comparison with the k6 Cloud.
Here you can see the **Request Made**, **Peak RPS**, and the **P95 Response Time** also have different value.
![image](https://user-images.githubusercontent.com/1778248/222077583-78bb1a45-8016-402e-a0b8-b1d4de2c77b7.png)
![image](https://user-images.githubusercontent.com/1778248/222077707-9f6d999d-fc12-423e-b130-18869e5b65be.png)

**Comment by soolch** [comment]
Hi @zzhao2010, may I know how do you solve your issue? Coz I am also using v0.2.0 but still the same.

**Comment by codebien** [comment]
@soolch are you sure you're using the latest version? Did you pull the latest commit from the `main` branch or from the latest tag? If yes, then can you post an anonymized script that allows us to reproduce your issue, please? You have an example a few lines before in [this comment ](https://github.com/grafana/xk6-output-prometheus-remote/issues/103#issuecomment-1446747395) using `test.k6.io`.

**Comment by soolch** [comment]
Hi @codebien, I have tried it once again, with the latest k6 binary, following the k6 documentation as it has updated that this is the official dashboard. But the issue still happens.
I tried using the following option
```
export const options = {
  scenarios: {
    'scenario-vehicle-content': {
      executor: 'ramping-arrival-rate',
      startRate: 50,
      timeUnit: '1m',
      preAllocatedVUs: 2,
      maxVUs: 50,
      stages: [
        { target: 50, duration: '1m' },
        { target: 100, duration: '1m' },
        { target: 100, duration: '1m' },
        { target: 200, duration: '1m' },
        { target: 200, duration: '1m' },
        { target: 300, duration: '1m' },
        { target: 300, duration: '1m' },
        { target: 400, duration: '1m' },
        { target: 400, duration: '1m' },
      ],
    },
  },
};
```
![image](https://user-images.githubusercontent.com/1778248/226258396-81cbd578-9ad5-4165-8347-5e9afaeeac15.png)
![image](https://user-images.githubusercontent.com/1778248/226258420-62b1148e-9ed6-4c21-a523-6bae1e1de13b.png)


But if i reduce my total test duration to 5m then the result shows correctly.
For the following stage configuration, the result is correct.
```
stages: [
        { target: 50, duration: '1m' },
        { target: 100, duration: '1m' },
        { target: 100, duration: '1m' },
        { target: 200, duration: '1m' },
        { target: 200, duration: '1m' }
      ],
```
![image](https://user-images.githubusercontent.com/1778248/226258166-2ca29eea-159d-4809-bae4-8b0880c50983.png)
![image](https://user-images.githubusercontent.com/1778248/226258210-b7c41c21-0ffe-40c0-95fd-2445ddb8a0f0.png)

**Comment by soolch** [comment]
Hi @jwcastillo, may I know are you able to simulate the same result at your side.

**Comment by soolch** [comment]
Hi @jwcastillo, would it be because of this 
https://k6.io/docs/results-output/real-time/prometheus-remote-write/#stale-trend-metrics

**Comment by codebien** [comment]
Hi @soolch,
do you use the dashboard with the Stale marker option enabled?

**Comment by soolch** [comment]
Hi @codebien, I didn't. Just that i read this stale option which also say 5mins. And the when i try search the result in the promtheus, those that are more than 5mins will be disappeared, which cause the grafana result incorrect.
